[package]
name = "cattleya"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-stream = "0.2.1"
anyhow = "1.0.86"
clap = { version = "4.5.3", features = ["derive"] }
memmap2 = "0.9.4"
rust-crypto = "0.2.36"
sha2 = "0.10.8"
thiserror = "1.0.63"
