name: CI for cattleya

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build-cache:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4    
          - name: Cache cargo
            uses: ./.github/actions/cache_cargo
          - name: build
            run: cargo build

    cargo-fmt:
        needs: build-cache
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Rust-toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                components: rustfmt
            - name: Cache cargo
              uses: ./.github/actions/cache_cargo
            - name: Run rustfmt
              run: cargo fmt --all -- --check

    cargo-test:
        needs: build-cache
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Rust-toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                components: clippy
            - name: Cache cargo
              uses: ./.github/actions/cache_cargo
            - name: Run clippy
              uses: giraffate/clippy-action@v1
              with:
                reporter: 'github-pr-review'
                github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Run tests
              run: cargo test
